version: '3.8'
services:
  db:
    image: postgres:16
    container_name: hotels_db
    env_file:
      - .env-non-dev
    ports:
      - 5432:5432
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      retries: 5

  redis:
    image: redis:7
    container_name: hotels_redis

  fastapi:
    build:
      context: .
    container_name: hotels_fastapi
    env_file:
      - .env-non-dev
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    command: ["/booking/docker/app.sh"]
    ports:
      - 9000:8000

  celery:
    build:
      context: .
    container_name: hotels_celery
    command: ["/booking/docker/celery.sh", "celery"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis

  flower:
    build:
      context: .
    container_name: hotels_flower
    command: ["/booking/docker/celery.sh", "flower"]
    env_file:
      - .env-non-dev
    depends_on:
      - redis
    ports:
      - 5555:5555





