[tool.black]
line-length = 88
target-version = ['py310']
exclude = 'migrations'

[tool.isort]
profile = "black"
multi_line_output = 3
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88
extend_skip = ["migrations"]

[tool.pyright]
include = ['app']
exclude = ['migrations']